manifest:
  self:
    path: application
  remotes:
    - name: nrf
      url-base: https://github.com/svankappel
  projects:
    - name: sdk-nrf
      remote: nrf
      path: nrf
      revision: v2.8.0
      import:
        path-prefix: external
      clone-depth: 1
